int _isupper(int c);
int _isdigit(int c);
int mul(int a, int b);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
void print_triangle(int size);
void print_number(int n);
int convert_day(int month, int day);
void print_remaining_days(int month, int day, int year);
void positive_or_negative(int i);
void print_alphabet(void);
void print_alphabet_x10(void);
int print_sign(int n);
int print_last_digit(int);
void times_table(void);
